# Generated by Django 5.2.17 on 2026-08-12 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=80, verbose_name='marque')),
                ('model_name', models.CharField(max_length=120, verbose_name='modèle')),
                ('year', models.PositiveSmallIntegerField(verbose_name='année')),
                ('price', models.PositiveBigIntegerField(verbose_name='prix (FCFA)')),
                ('mileage', models.PositiveIntegerField(verbose_name='kilométrage (km)')),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], default='essence', max_length=20, verbose_name='carburant')),
                ('transmission', models.CharField(choices=[('automatique', 'Automatique'), ('manuelle', 'Manuelle')], default='automatique', max_length=20, verbose_name='transmission')),
                ('city', models.CharField(max_length=120, verbose_name='ville')),
                ('condition', models.CharField(choices=[('neuf', 'Neuf'), ('occasion', 'Occasion')], default='occasion', max_length=20, verbose_name='état')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('is_verified', models.BooleanField(default=False, verbose_name='inspecté par Djona')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='image')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.vehicle')),
            ],
            options={
                'verbose_name': 'image véhicule',
                'verbose_name_plural': 'images véhicule',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.vehicle')),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'vehicle'), name='unique_user_favorite'), models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('session_key', 'vehicle'), name='unique_session_favorite')],
            },
        ),
    ]
