# Generated by Django 5.2.17 on 2026-08-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_vehicle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
