# Generated by Django 5.0.14 on 2026-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_vehicle_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='source_annonce_id',
            field=models.PositiveIntegerField(blank=True, help_text='Référence vers annonces.id (djona_vendor) si ce véhicule provient de la synchro back-office.', null=True, unique=True, verbose_name="id annonce d'origine"),
        ),
    ]
