# Generated by Django 5.0.14 on 2026-09-03 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_vehicle_source_annonce_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_vendeur_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='téléphone')),
                ('type_compte', models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='raison sociale')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sellers/', verbose_name='logo')),
                ('member_since', models.DateTimeField(verbose_name='membre depuis')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'vendeur',
                'verbose_name_plural': 'vendeurs',
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='catalog.seller'),
        ),
    ]
