# Generated by Django 5.0.14 on 2026-09-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seller_vehicle_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, choices=[('abidjan_cocody', 'Abidjan, Cocody'), ('abidjan_marcory', 'Abidjan, Marcory'), ('abidjan_koumassi', 'Abidjan, Koumassi'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké')], max_length=30, verbose_name='ville'),
        ),
    ]
