# Generated by Django 5.0.14 on 2026-09-13 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_seller_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='catalog.vehicle')),
            ],
            options={
                'verbose_name': 'intérêt acheteur',
                'verbose_name_plural': 'intérêts acheteurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
