# Generated by Django 5.0.14 on 2026-09-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sellers/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='vehicles/', verbose_name='image'),
        ),
    ]
