# Generated by Django 5.0.14 on 2026-10-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_seller_logo_alter_vehicleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_verified_company',
            field=models.BooleanField(default=False, help_text="Justificatif RCCM validé par l'équipe Djona (copié depuis vendor.Profil.entreprise_verifiee).", verbose_name='entreprise vérifiée'),
        ),
        migrations.AddField(
            model_name='seller',
            name='showroom_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='adresse du showroom'),
        ),
    ]
