# Generated by Django 5.0.14 on 2026-10-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seller_showroom_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('occasion', 'Occasion')], max_length=20, verbose_name='état'),
        ),
    ]
