# Generated by Django 6.1 on 2026-08-28 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('ville', models.CharField(blank=True, choices=[('abidjan_cocody', 'Abidjan, Cocody'), ('abidjan_marcory', 'Abidjan, Marcory'), ('abidjan_koumassi', 'Abidjan, Koumassi'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké')], max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('langue', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('notif_email', models.BooleanField(default=True)),
                ('notif_whatsapp', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
