/**
 * Tokens repris tels quels depuis _mockups/_assets/djona_automotive_system/DESIGN.md
 * (source de vérité du design system — AGENTS.md §6). Ne pas dupliquer ce fichier
 * ailleurs : un seul tailwind.config.js pour tout le projet.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './templates/**/*.html',
    './apps/**/templates/**/*.html',
    './apps/**/*.py',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f8f9f9',
        'surface-dim': '#d9dada',
        'surface-bright': '#f8f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f4',
        'surface-container': '#edeeee',
        'surface-container-high': '#e7e8e8',
        'surface-container-highest': '#e1e3e3',
        'on-surface': '#191c1c',
        'on-surface-variant': '#41474e',
        'inverse-surface': '#2e3131',
        'inverse-on-surface': '#f0f1f1',
        outline: '#72787f',
        'outline-variant': '#c1c7cf',
        'surface-tint': '#2f6388',
        primary: '#003b5a',
        'on-primary': '#ffffff',
        'primary-container': '#1a5276',
        'on-primary-container': '#94c5ee',
        'inverse-primary': '#9bccf6',
        secondary: '#865300',
        'on-secondary': '#ffffff',
        'secondary-container': '#fea520',
        'on-secondary-container': '#694000',
        tertiary: '#26384b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3d4f63',
        'on-tertiary-container': '#aec1d8',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#cbe6ff',
        'primary-fixed-dim': '#9bccf6',
        'on-primary-fixed': '#001e30',
        'on-primary-fixed-variant': '#0e4b6e',
        'secondary-fixed': '#ffddb9',
        'secondary-fixed-dim': '#ffb961',
        'on-secondary-fixed': '#2b1700',
        'on-secondary-fixed-variant': '#663e00',
        'tertiary-fixed': '#d1e4fc',
        'tertiary-fixed-dim': '#b5c8e0',
        'on-tertiary-fixed': '#091d2e',
        'on-tertiary-fixed-variant': '#36485c',
        background: '#f8f9f9',
        'on-background': '#191c1c',
        'surface-variant': '#e1e3e3',
      },
      fontFamily: {
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'container-margin-mobile': '16px',
        'container-margin-desktop': '32px',
        gutter: '16px',
        'section-gap': '48px',
      },
      boxShadow: {
        signature: '0px 4px 12px rgba(26, 82, 118, 0.08)',
      },
      maxWidth: {
        page: '1280px',
      },
    },
  },
  plugins: [],
}
