# Generated by Django 5.0.14 on 2026-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=80)),
                ('modele', models.CharField(max_length=80)),
                ('annee', models.PositiveIntegerField()),
                ('prix', models.PositiveIntegerField()),
                ('kilometrage', models.PositiveIntegerField()),
                ('carburant', models.CharField(max_length=20)),
                ('boite_vitesses', models.CharField(max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('publiee', 'Publiée'), ('refusee', 'Refusée')], max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'annonces',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnoncePhotoMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/%Y/%m/')),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'annonce_photos',
                'ordering': ['ordre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VendeurMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vendeur_utilisateurs',
                'managed': False,
            },
        ),
    ]
