# Generated by Django 5.0.14 on 2026-10-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilMirror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, max_length=30)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('raison_sociale', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'app_profil',
                'managed': False,
            },
        ),
    ]
