# Generated by Django 5.2.17 on 2026-08-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
