# Generated by Django 5.0.14 on 2026-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='logo')),
                ('website_url', models.URLField(blank=True, verbose_name='site web')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('publish', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'partenaires',
                'ordering': ['order', 'name'],
            },
        ),
    ]
