# Generated by Django 5.0.14 on 2026-09-25 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nom')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'type de véhicule de transport',
                'verbose_name_plural': 'types de véhicules de transport',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True, verbose_name='numéro de demande')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('requester_type', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20, verbose_name='type de demandeur')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name="nom de l'entreprise")),
                ('quantity', models.CharField(max_length=5, verbose_name='nombre de véhicules')),
                ('loading_date', models.DateField(verbose_name='date de chargement')),
                ('loading_place', models.CharField(max_length=200, verbose_name='lieu de chargement')),
                ('delivery_place', models.CharField(max_length=200, verbose_name='lieu de livraison')),
                ('message', models.TextField(blank=True, verbose_name='informations complémentaires')),
                ('status', models.CharField(choices=[('nouvelle', 'Nouvelle demande'), ('en_traitement', 'En traitement'), ('traitee', 'Traitée'), ('annulee', 'Annulée')], default='nouvelle', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de la demande')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.transportvehicletype', verbose_name='type de véhicule')),
            ],
            options={
                'verbose_name': 'demande de transport',
                'verbose_name_plural': 'demandes de transport',
                'ordering': ['-created_at'],
            },
        ),
    ]
