# Generated by Django 5.0.14 on 2026-10-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_transport_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='nom complet')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('subject', models.CharField(choices=[('achat', 'Acheter un véhicule'), ('vente', 'Vendre mon véhicule'), ('transport', 'Transport & logistique'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='achat', max_length=20, verbose_name='objet')),
                ('message', models.TextField(verbose_name='message')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_traitement', 'En traitement'), ('traite', 'Traité')], default='nouveau', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
