# Generated by Django 5.0.14 on 2026-10-03 01:35

from django.db import migrations, models


def seed(apps, schema_editor):
    apps.get_model('core', 'SiteContact').objects.update_or_create(pk=1, defaults={
        'phone': '+225 01 41 60 27 53',
        'whatsapp': '+225 01 41 60 27 53',
        'email': 'contact@djona.tech',
        'address': 'Angré 9ème tranche, non loin de CGK',
        'city': "Abidjan, Côte d'Ivoire",
    })


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=255, verbose_name='siège social')),
                ('city', models.CharField(max_length=100, verbose_name='ville')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'coordonnées du site',
                'verbose_name_plural': 'coordonnées du site',
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
