# Generated by Django 5.0.14 on 2026-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('achat', 'Acheter un véhicule'), ('vente', 'Vendre mon véhicule'), ('transport', 'Transport & logistique'), ('partenariat', 'Partenariat'), ('autre', 'Autre'), ('question', 'Question (FAQ)')], default='achat', max_length=20, verbose_name='objet'),
        ),
    ]
