# Generated by Django 5.0.14 on 2026-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_subject_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontact',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitecontact',
            name='tiktok_url',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
    ]
